import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from './Components/Sections/About/About'
import Banner from './Components/Sections/Banner'
import Certification from './Components/Sections/Certification/Certification'
import Clients from './Components/Sections/Clients/Clients'
import Strength from './Components/Sections/Strength/Strength'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HDF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner/>
        <About/>
        <Strength/>
        <Clients/>
        <Certification/>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
